name: nf-core-rnafusion-1.0.1
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - anaconda::openjdk=8.0.152 # Needed for FastQC - conda build hangs without this
  - bioconda::fastqc=0.11.8
  - bioconda::star=2.6.1b # update STAR-Fusion and Fusion-Inspector
  - bioconda::multiqc=1.7
  - conda-forge::r-data.table=1.12.0
  - conda-forge::r-gplots=3.0.1.1
  - bioconda::bioconductor-edger=3.24.1
  - conda-forge::r-markdown=0.9
  - bioconda::fusion-report=1.0.0
