name: nf-core-rnafusion-1.0dev
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - fastqc=0.11.7
  - multiqc=1.6
  - gmap=2018.03.25
  - star=2.6.1a
  - star-fusion=1.4.0
  - trinity=2.6.6
  - fusion-inspector=1.2.0
