name: fusionreport
description: fusionreport
keywords:
  - sort
tools:
  - fusionreport:
      description: fusionreport
      homepage: https://github.com/ndaniel/fusioncatcher/
      documentation: https://github.com/ndaniel/fusioncatcher/blob/master/doc/manual.md
      tool_dev_url: https://github.com/ndaniel/fusioncatcher/
      doi: "10.1101/011650"
      licence: ['GPL v3']

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - reference:
      type: path
      description: DB
      pattern: "*"
  - fusions:
      type: path
      description: File contains fusions which pass all of Arriba's filters.
      pattern: "*.fusions.tsv"

output:
  - versions:
        type: file
        description: File containing software versions
        pattern: "versions.yml"

authors:
  - "@praveenraj2018"
