name: kallisto_quant
description: runs the kallisto quantification algorithm
  - quant
tools:
  - kallisto:
      description: Quantifying abundances of transcripts from bulk and single-cell RNA-Seq data, or more generally of target sequences using high-throughput sequencing reads.
      homepage: https://pachterlab.github.io/kallisto/
      documentation: https://pachterlab.github.io/kallisto/manual
      tool_dev_url: https://github.com/pachterlab/kallisto
      doi: ""
      licence: ["BSD-2-Clause"]

input:
  - fasta:
      type: file
      description: genome fasta file
      pattern: "*.{fasta*}"
  - reference:
      type: directory
      description: Path to kallisto index
      pattern: "*"

output:
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - fusions:
      type: file
      description: fusions
      pattern: "*.txt"

authors:
  - "@rannick"
