name: fusioncatcher_download
description: Build genome for fusioncatcher
keywords:
  - sort
tools:
  - fusioncatcher:
      description: Build genome for fusioncatcher
      homepage: https://github.com/ndaniel/fusioncatcher/
      documentation: https://github.com/ndaniel/fusioncatcher/blob/master/doc/manual.md
      tool_dev_url: https://github.com/ndaniel/fusioncatcher/
      doi: "10.1101/011650"
      licence: ['GPL v3']

input:
  - organism:
      type: value
      description: Organism for which the data is downloaded from Ensembl database and built
      pattern: "*"

output:
  - version:
      type: file
      description: File containing software version
      pattern: "*.{version.txt}"
  - resources:
      type: directory
      description: directory containing the genome resource files required for fusioncatcher
      pattern: "fusioncatcher-genome"

authors:
  - "@praveenraj2018"
